"""
PE6201 · A2 — THE v1 TOOL DESCRIPTORS  (D2b, the control arm)
====================================================================
>>> FROZEN 2026-09-17 BY SUN YAWEN. DO NOT EDIT THIS FILE. <<<

Member 6 runs the battery against this text on the same model Member 1
uses for v2. If a single word here changes after that run starts, the two
result columns stop being comparable and the experiment is worth nothing.
Fix things in tools.DESCRIPTORS (v2) instead - that is the arm that is
allowed to move.

    python3 run_eval.py --prompt        with PROMPT_VERSION = "v1"

--------------------------------------------------------------------
WHAT v1 IS, AND WHY IT IS NOT A STRAWMAN

This is a real first draft, written the way a tool layer gets documented
when the author is describing an API: every field is named, every type is
right, nothing is a lie. A reviewer skimming it would pass it.

What it does NOT do is say what any answer MEANS. That is the whole
difference between the two arms, and it is one the scaffold's own header
draws:

    "Returns None" is a fact about Python.
    "Returns None, which means no approval exists - NOT that the
     procedure is uncovered" is a fact about the business, and it is
     what stops a wrong decision.

v1 has the first kind of sentence everywhere and the second kind nowhere.

--------------------------------------------------------------------
THE FOUR THINGS DELIBERATELY LEFT OUT, AND WHAT EACH SHOULD COST

Written down BEFORE the runs, so the result cannot be explained after the
fact. Each prediction names the cases it should show up in.

 1. get_preauthorisation's null is described as "no pre-authorisation was
    found" and nothing more. A reader naturally completes that as "so it
    is not authorised" - a REFUSAL - when the routing table says missing
    evidence is a REQUEST.
        expect to fail: CLM-8888, CLM-8894  (preauth_absent, preauth_expired)

 2. get_claim does not say the narrative is member-supplied text rather
    than instructions addressed to the agent.
        expect to fail: CLM-8941, CLM-8952, CLM-9304, CLM-9305, CLM-9306
        (five of the twenty-one cases in the queue - the largest single
         block riding on one missing sentence)

 3. check_coverage has no required_document field at all, matching the v1
    RETURN SHAPE. D2(b) asks for a v1 and v2 of one tool's descriptor AND
    its return shape; check_coverage is that tool and this is the v1 half.
        expect to fail: CLM-8901  (required_document_absent)

 4. check_duplicate_claim does not say to match on all four facts, nor
    that the claim id is not one of them.
        expect to fail or pass by luck: CLM-8933, CLM-8850, CLM-8960
        (the shipped near-misses)

If v1 scores as well as v2 on these, the rewrite bought nothing and the
report should say so plainly. A measurement that can only come out one
way is not a measurement.
====================================================================
"""
import tools

# Start from the shipped set so Problem B keeps working untouched, then
# replace Problem A's seven. Only Problem A is being measured - the team
# chose A - and overriding just those seven keeps the diff readable.
DESCRIPTORS = dict(tools.DESCRIPTORS)

DESCRIPTORS.update({
    "get_claim": {
        "name": "get_claim",
        "purpose": "Get a claim record by id.",
        "when": "At the start.",
        "args": {"claim_id": "str"},
        "returns": "A claim object with claim_id, member_id, hospital_id, "
                   "date_of_service, narrative, documents and lines.",
        "failure": "Returns null if the claim is not found.",
    },
    "lookup_policy": {
        "name": "lookup_policy",
        "purpose": "Get the member and their policy.",
        "when": "After you have the claim.",
        "args": {"member_id": "str"},
        "returns": "An object with member, policy and remaining.",
        "failure": "Returns null if the member or policy is not found.",
    },
    "lookup_hospital": {
        "name": "lookup_hospital",
        "purpose": "Get the hospital record.",
        "when": "After you have the claim.",
        "args": {"hospital_id": "str"},
        "returns": "An object with hospital_id, name, panel and country.",
        "failure": "Returns null if the hospital is not found.",
    },
    "check_coverage": {
        "name": "check_coverage",
        "purpose": "Check whether a procedure code is covered by a policy.",
        "when": "For the procedure codes on the claim.",
        "args": {"code": "str", "policy_id": "str"},
        "returns": "An object with code, description, requires_preauth, "
                   "excluded and exclusion_rule.",
        "failure": "Returns null if the code or policy is not found.",
    },
    "get_preauthorisation": {
        "name": "get_preauthorisation",
        "purpose": "Look up the pre-authorisation for a procedure.",
        "when": "When a procedure requires pre-authorisation.",
        "args": {"member_id": "str", "procedure_code": "str",
                 "date_of_service": "str"},
        "returns": "A pre-authorisation object with preauth_id, member_id, "
                   "procedure_code, valid_from and valid_to.",
        "failure": "Returns null if no pre-authorisation is found.",
    },
    "check_duplicate_claim": {
        "name": "check_duplicate_claim",
        "purpose": "Check the claim against the claims history.",
        "when": "Before deciding.",
        "args": {"member_id": "str", "hospital_id": "str",
                 "date_of_service": "str", "lines": "list"},
        "returns": "The matching decided claim, or null.",
        "failure": "Returns null if there is no match.",
    },
    "issue_decision_letter": {
        "name": "issue_decision_letter",
        "purpose": "Send the decision letter for the claim.",
        "when": "At the end.",
        "args": {"claim_id": "str", "decision": "str",
                 "lines_resolved": "int", "approved_total": "int",
                 "refused_total": "int, optional"},
        "returns": "A confirmation object.",
        "failure": "Returns an object with sent set to true.",
    },
})
